description = """
A simpler counter component.
"""
motivation="""
This example shows how to write the most basic component.
- the component owns a state (the count)
- some browser events (onclick in this case) will update this state
- each time the state change, it will be rerendered
"""
related="""
See [counter_without_macro](#counter_without_macro) and [counter_url_query](#counter_url_query) for other versions of the same component
"""
features = ["nightly"]
links = ["counter_without_macro"]
