description="pass a function that returns html as a prop"
motivation="""
Illustrates how you can pass a function that returns html as a prop,
with the help of callbacks
"""
related="""
https://docs.rs/leptos/latest/leptos/callback/index.html
"""

features=["nightly"]
