description="pass either a dynamic or a static property"
motivation="""
illustrates how to use `MaybeSignal` to pass either a dynamic, either a static prop
"""
related="""
<https://docs.rs/leptos/latest/leptos/enum.MaybeSignal.html>
"""
features=["nightly"]
